### ISSUE TITLE
ifc6410

### ISSUE THREAD

**Issue by EmbeddedAndroid** [freedreno-zz/kernel-msm#1]
Hi,

I was curious if you are booting his kernel on an IFC6410 board? I'm building this kernel (ifc6410_rob_defconfig, ifc6410-drm branch) natively on the target, and having no success creating a bootable boot.img. I used abootimg, and have had no luck :(

This kernel works:

http://people.freedesktop.org/%7Erobclark/f19/ifc6410-boot-drm.img

However anything I produce from this tree does not. Could you post some basic instructions of how you are creating/packing the boot.img? TIA

Cheers

**Comment by robclark** [comment]
fwiw,

$ cat mkbootimg.sh 
abootimg --create ifc6410-boot.img -k ../msm/arm/arch/arm/boot/zImage -f ./bootimg.cfg -r initramfs-3.4.0-g0f0fed7-00108-gf736ca1-dirty.img 

$ cat bootimg.cfg
bootsize = 0x1600000
pagesize = 0x800
kerneladdr = 0x80208000
secondaddr = 0x82100000
ramdiskaddr = 0x82508000
tagsaddr = 0x80200100
name = ifc6410
cmdline = earlyprintk=serial,ttyHSL0,115200,n8 console=ttyHSL0,115200,n8 console=tty0 root=/dev/sda3 rootwait plymouth.ignore-serial-consoles rhgb

---

note that you can use abootimg -x to extract the ramdisk, .cfg, etc from an existing boot .img

**Comment by EmbeddedAndroid** [comment]
thank you. exactly what I was looking for.
